### PR TITLE
187

### PR DESCRIPTION
**Pull request by lprivette**
Flags are not cleared in graph clear

### CODE REVIEW

**Comment by ghost** [comment]
This is a great addition! Clears everything perfectly. 
I noticed one bug: some change in `map.component.ts` causes the popup to print one entry per number of results. For example: 

Before: 

image

After:

image

I agree that flags shouldn't be cleared. Maybe name the clear button to `Clear Filters` just to prevent any user confusion on that? Same for the map because user might want to clear filters before they plotted any points, so there may or may not be any map to clear.

**Comment by ghost** [comment]
Also! Changelog. I almost forgot :)

**Comment by lprivette** [comment]
lol dang changelog! 

Fixing bug, changing button name, and adding changelog, will comment again when changes are pushed to this branch/PR

**Comment by lprivette** [comment]
@kathymd pushed those changes

**Comment by ghost** [comment]
Pop-ups look good! Would it be possible to close them when the map is reset? For example, I when I have this pop-up open and click clear, everything resets, but pop-up still shows:
image

**Comment by lprivette** [comment]
popups should clear with latest push to 187

**Review by ghost — APPROVED** [review]

**Pull request merged**
